/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
    avatar: string | null;
    created_at: Generated<Timestamp>;
    display_name: string | null;
    id: string;
    is_bot: Generated<boolean>;
    updated_at: Generated<Timestamp>;
    username: string;
}

export interface DB {
    users: Users;
}
