name: Mark Stale Issues and Pull Requests

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and pull requests
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: |
            pinned
            security
            bug
            enhancement
            documentation
          exempt-pr-labels: |
            pinned
            security
            bug
            enhancement
            documentation
          exempt-all-milestones: true
          exempt-all-assignees: true
          exempt-all-reviewers: true
